airflow_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USERNAME', 'myuser') }}"
      password: "{{ env_var('DBT_PASSWORD', 'mypassword') }}"
      port: "{{ env_var('DBT_PORT', '5432') | as_number }}"
      dbname: "{{ env_var('DBT_DATABASE', 'dev') }}"
      schema: dev
      threads: 2
      connect_timeout: 10
      retries: 1
    
    prod:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USERNAME', 'myuser') }}"
      password: "{{ env_var('DBT_PASSWORD', 'mypasword') }}"
      port: "{{ env_var('DBT_PORT', '5432') | as_number }}"
      dbname: "{{ env_var('DBT_DATABASE', 'prod') }}"
      schema: dbt
      threads: 2
      connect_timeout: 10
      retries: 1

    ci:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USERNAME', 'myuser') }}"
      password: "{{ env_var('DBT_PASSWORD', 'mypasword') }}"
      port: "{{ env_var('DBT_PORT', '5432') | as_number }}"
      dbname: "{{ env_var('DBT_DATABASE', 'ci') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'ci') }}"
      threads: 2
      connect_timeout: 10
      retries: 1
