starrocksOperator:
  enabled: true

starrocksCluster:
  name: "starrocks"
  namespace: "starrocks"
  enabledCn: false

starrocksFESpec:
  replicas: 3
  image:
    repository: starrocks/fe-ubuntu
    tag: 3.0.1

  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 4
      memory: 8Gi

  # the config for start fe. the base information as follows.
  config: |
    LOG_DIR = ${STARROCKS_HOME}/log
    DATE = "$(date +%Y%m%d-%H%M%S)"
    JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:${LOG_DIR}/fe.gc.log.$DATE"
    JAVA_OPTS_FOR_JDK_9="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xlog:gc*:${LOG_DIR}/fe.gc.log.$DATE:time"
    http_port = 8030
    rpc_port = 9020
    query_port = 9030
    edit_log_port = 9010
    mysql_service_nio_enabled = true   
    sys_log_level = INFO
    run_mode=shared_data
    aws_s3_path=starrocks/data
    aws_s3_endpoint=http://192.168.49.1:9000
    aws_s3_region=aws-global
    aws_s3_access_key=admin
    aws_s3_secret_key=M!Secr3t

# starrocksCnSpec:
#   resource:
#     limits:
#       cpu: 1
#       memory: 4Gi
#     requests:
#       cpu: 4
#       memory: 8Gi

starrocksBeSpec:
  replicas: 3
  image:
    repository: starrocks/be-ubuntu
    tag: 2.5.5
  resource:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 4
      memory: 8Gi
  config: |
    be_port = 9060
    webserver_port = 8040
    heartbeat_service_port = 9050
    brpc_port = 8060
    sys_log_level = INFO
    default_rowset_type = beta
